version: '2.1'

services:
  graphql-server:
    image: graphql-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8088:8088
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js